### ISSUE TITLE
maybe a typo of setup.py

### ISSUE THREAD

**Issue by arx7** [gudrunhe/gosam#1]
I fail to compile gosam with `gosam_installer.py`, which reports
```
subprocess.CalledProcessError: Command '['git', '--git-dir=.git', 'rev-parse', '--short=7', 'HEAD']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    GIT_REVISION = get_git_revision()
  File "setup.py", line 37, in get_git_revision
    return line.split("-", 1)[1].strip()
IndexError: list index out of range
```
Additional info.:
Cent OS
git version = 2.14.5
gcc version = 6.3.1

Maybe, it should be `return line.split(":", 1)[1].strip()` ?

**Comment by magv** [comment]
No, `"-"` is correct; PKG-INFO should have `Version: 2.x.x-gitrevision`. It does not because we are probably fetching the wrong tarball. Sorry about this, I'll try to make it work.

Thanks for testing.

**Comment by magv** [comment]
Try installing again now. It should work.

**Comment by arx7** [comment]
Thanks! It works now.
