### ISSUE TITLE
Migrate setup.py to setuptools

### ISSUE THREAD

**Issue by iarspider** [gudrunhe/gosam#2]
In Python 3.9 and 3.10, importing distutils will raise depreation warning, and starting with 3.11 distutils will no longer be installed by default - see [PEP-632](https://www.python.org/dev/peps/pep-0632/). \

Maybe you could migrate `setup.py` script to use setuptools (there is [a guide](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html) on how to do this), or even [Flit](https://pypi.org/project/flit/)?

**Comment by andriish** [comment]
Hi @iarspider, is were the changes in #3 sufficient for you?

**Comment by iarspider** [comment]
Hi @andriish ,

yes, thank you!
