### ISSUE TITLE
Remove git-hash fron version number

### ISSUE THREAD

**Issue by Romendakil** [gudrunhe/gosam#9]
The git-hash is no longer accepted in the versioning for modern python versions, at least for python 3.12 and newer. 
I know that a newer build system is imminent, but since then I cannot install GoSam anymore as the installer always downloads
an installation.py script and overwrites my changes

**Comment by Romendakil** [comment]
Maybe you could actually work with a four-digit system, like 2.1.1.1 etc.

**Comment by Jens-Braun** [comment]
Dear @Romendakil, in the new release 2.1.2, the versioning scheme of GoSam is compatible with modern Python versions again.
